spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: query-burst-msa-ranking
      auto-offset-reset: earliest

data:
  init:
    window-hours: 24
    products-per-hour: 5000
