spring:
  application:
    name: query-burst-member-service
  profiles:
    active: local
  jpa:
    open-in-view: false

server:
  port: 18114

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
        hikaricp.connections: true
      slo:
        http.server.requests: 50ms, 100ms, 200ms, 500ms, 1s, 5s
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${TEMPO_ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}

loki:
  url: ${LOKI_URL:http://localhost:3100/loki/api/v1/push}
