server:
  port: 8090

spring:
  application:
    name: query-burst

  profiles:
    active: local   # 기본 프로파일

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 1000
          order_inserts: true
          order_updates: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF