package com.booster.ddayservice.specialday.domain;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum CountryCode {

    AD("Andorra", Timezone.EUROPE_ANDORRA),
    AL("Albania", Timezone.EUROPE_TIRANE),
    AM("Armenia", Timezone.ASIA_YEREVAN),
    AR("Argentina", Timezone.AMERICA_ARGENTINA_BUENOS_AIRES),
    AT("Austria", Timezone.EUROPE_VIENNA),
    AU("Australia", Timezone.AUSTRALIA_SYDNEY),
    AX("Åland Islands", Timezone.EUROPE_HELSINKI),
    BA("Bosnia and Herzegovina", Timezone.EUROPE_SARAJEVO),
    BB("Barbados", Timezone.AMERICA_BARBADOS),
    BE("Belgium", Timezone.EUROPE_BRUSSELS),
    BG("Bulgaria", Timezone.EUROPE_SOFIA),
    BJ("Benin", Timezone.AFRICA_PORTO_NOVO),
    BO("Bolivia", Timezone.AMERICA_LA_PAZ),
    BR("Brazil", Timezone.AMERICA_SAO_PAULO),
    BS("Bahamas", Timezone.AMERICA_NASSAU),
    BW("Botswana", Timezone.AFRICA_GABORONE),
    BY("Belarus", Timezone.EUROPE_MINSK),
    BZ("Belize", Timezone.AMERICA_BELIZE),
    CA("Canada", Timezone.AMERICA_TORONTO),
    CD("DR Congo", Timezone.AFRICA_KINSHASA),
    CG("Congo", Timezone.AFRICA_BRAZZAVILLE),
    CH("Switzerland", Timezone.EUROPE_ZURICH),
    CL("Chile", Timezone.AMERICA_SANTIAGO),
    CN("China", Timezone.ASIA_SHANGHAI),
    CO("Colombia", Timezone.AMERICA_BOGOTA),
    CR("Costa Rica", Timezone.AMERICA_COSTA_RICA),
    CU("Cuba", Timezone.AMERICA_HAVANA),
    CY("Cyprus", Timezone.ASIA_NICOSIA),
    CZ("Czechia", Timezone.EUROPE_PRAGUE),
    DE("Germany", Timezone.EUROPE_BERLIN),
    DK("Denmark", Timezone.EUROPE_COPENHAGEN),
    DO("Dominican Republic", Timezone.AMERICA_SANTO_DOMINGO),
    EC("Ecuador", Timezone.AMERICA_GUAYAQUIL),
    EE("Estonia", Timezone.EUROPE_TALLINN),
    EG("Egypt", Timezone.AFRICA_CAIRO),
    ES("Spain", Timezone.EUROPE_MADRID),
    FI("Finland", Timezone.EUROPE_HELSINKI),
    FO("Faroe Islands", Timezone.ATLANTIC_FAROE),
    FR("France", Timezone.EUROPE_PARIS),
    GA("Gabon", Timezone.AFRICA_LIBREVILLE),
    GB("United Kingdom", Timezone.EUROPE_LONDON),
    GD("Grenada", Timezone.AMERICA_GRENADA),
    GE("Georgia", Timezone.ASIA_TBILISI),
    GG("Guernsey", Timezone.EUROPE_GUERNSEY),
    GH("Ghana", Timezone.AFRICA_ACCRA),
    GI("Gibraltar", Timezone.EUROPE_GIBRALTAR),
    GL("Greenland", Timezone.AMERICA_NUUK),
    GM("Gambia", Timezone.AFRICA_BANJUL),
    GR("Greece", Timezone.EUROPE_ATHENS),
    GT("Guatemala", Timezone.AMERICA_GUATEMALA),
    GY("Guyana", Timezone.AMERICA_GUYANA),
    HK("Hong Kong", Timezone.ASIA_HONG_KONG),
    HN("Honduras", Timezone.AMERICA_TEGUCIGALPA),
    HR("Croatia", Timezone.EUROPE_ZAGREB),
    HT("Haiti", Timezone.AMERICA_PORT_AU_PRINCE),
    HU("Hungary", Timezone.EUROPE_BUDAPEST),
    ID("Indonesia", Timezone.ASIA_JAKARTA),
    IE("Ireland", Timezone.EUROPE_DUBLIN),
    IM("Isle of Man", Timezone.EUROPE_ISLE_OF_MAN),
    IS("Iceland", Timezone.ATLANTIC_REYKJAVIK),
    IT("Italy", Timezone.EUROPE_ROME),
    JE("Jersey", Timezone.EUROPE_JERSEY),
    JM("Jamaica", Timezone.AMERICA_JAMAICA),
    JP("Japan", Timezone.ASIA_TOKYO),
    KE("Kenya", Timezone.AFRICA_NAIROBI),
    KR("South Korea", Timezone.ASIA_SEOUL),
    KZ("Kazakhstan", Timezone.ASIA_ALMATY),
    LI("Liechtenstein", Timezone.EUROPE_VADUZ),
    LS("Lesotho", Timezone.AFRICA_MASERU),
    LT("Lithuania", Timezone.EUROPE_VILNIUS),
    LU("Luxembourg", Timezone.EUROPE_LUXEMBOURG),
    LV("Latvia", Timezone.EUROPE_RIGA),
    MA("Morocco", Timezone.AFRICA_CASABLANCA),
    MC("Monaco", Timezone.EUROPE_MONACO),
    MD("Moldova", Timezone.EUROPE_CHISINAU),
    ME("Montenegro", Timezone.EUROPE_PODGORICA),
    MG("Madagascar", Timezone.INDIAN_ANTANANARIVO),
    MK("North Macedonia", Timezone.EUROPE_SKOPJE),
    MN("Mongolia", Timezone.ASIA_ULAANBAATAR),
    MS("Montserrat", Timezone.AMERICA_MONTSERRAT),
    MT("Malta", Timezone.EUROPE_MALTA),
    MX("Mexico", Timezone.AMERICA_MEXICO_CITY),
    MZ("Mozambique", Timezone.AFRICA_MAPUTO),
    NA("Namibia", Timezone.AFRICA_WINDHOEK),
    NE("Niger", Timezone.AFRICA_NIAMEY),
    NG("Nigeria", Timezone.AFRICA_LAGOS),
    NI("Nicaragua", Timezone.AMERICA_MANAGUA),
    NL("Netherlands", Timezone.EUROPE_AMSTERDAM),
    NO("Norway", Timezone.EUROPE_OSLO),
    NZ("New Zealand", Timezone.PACIFIC_AUCKLAND),
    PA("Panama", Timezone.AMERICA_PANAMA),
    PE("Peru", Timezone.AMERICA_LIMA),
    PG("Papua New Guinea", Timezone.PACIFIC_PORT_MORESBY),
    PH("Philippines", Timezone.ASIA_MANILA),
    PL("Poland", Timezone.EUROPE_WARSAW),
    PR("Puerto Rico", Timezone.AMERICA_PUERTO_RICO),
    PT("Portugal", Timezone.EUROPE_LISBON),
    PY("Paraguay", Timezone.AMERICA_ASUNCION),
    RO("Romania", Timezone.EUROPE_BUCHAREST),
    RS("Serbia", Timezone.EUROPE_BELGRADE),
    RU("Russia", Timezone.EUROPE_MOSCOW),
    SE("Sweden", Timezone.EUROPE_STOCKHOLM),
    SG("Singapore", Timezone.ASIA_SINGAPORE),
    SI("Slovenia", Timezone.EUROPE_LJUBLJANA),
    SJ("Svalbard and Jan Mayen", Timezone.ARCTIC_LONGYEARBYEN),
    SK("Slovakia", Timezone.EUROPE_BRATISLAVA),
    SM("San Marino", Timezone.EUROPE_SAN_MARINO),
    SR("Suriname", Timezone.AMERICA_PARAMARIBO),
    SV("El Salvador", Timezone.AMERICA_EL_SALVADOR),
    TN("Tunisia", Timezone.AFRICA_TUNIS),
    TR("Türkiye", Timezone.EUROPE_ISTANBUL),
    UA("Ukraine", Timezone.EUROPE_KYIV),
    US("United States", Timezone.AMERICA_NEW_YORK),
    UY("Uruguay", Timezone.AMERICA_MONTEVIDEO),
    VA("Vatican City", Timezone.EUROPE_VATICAN),
    VE("Venezuela", Timezone.AMERICA_CARACAS),
    VN("Vietnam", Timezone.ASIA_HO_CHI_MINH),
    ZA("South Africa", Timezone.AFRICA_JOHANNESBURG),
    ZW("Zimbabwe", Timezone.AFRICA_HARARE),
    ;

    private final String displayName;
    private final Timezone defaultTimezone;
}
