server:
  port: 0

spring:
  application:
    name: shopping-service
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:h2:mem:shoppingservicedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: bW9ja1NlY3JldEtleUZvckRldmVsb3BtZW50T25seUF0TGVhc3QyNTZCaXRzTG9uZw==
  access-token-expiry: 1800000    # 30분 (ms)
  refresh-token-expiry: 604800000 # 7일 (ms)


